# Generated by Django 4.0.1 on 2022-01-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('intro', models.TextField()),
                ('area', models.CharField(max_length=15)),
                ('party_num', models.IntegerField(default=1)),
            ],
        ),
    ]
